INSERT INTO globals (gl_name, gl_index, gl_value) VALUES
('ai_dictation_enabled', 0, '1'),
('ai_dictation_default_mode', 0, 'hpc'),
('ai_dictation_specialty_template', 0, 'obgyn'),
('ai_dictation_auto_populate', 0, '1'),
('ai_dictation_require_review', 0, '1'),
('ai_dictation_phi_scrub', 0, '1'),
('ai_dictation_scrub_patient_name', 0, '1'),
('ai_dictation_scrub_dob', 0, '1'),
('ai_dictation_scrub_mrn', 0, '1'),
('ai_dictation_scrub_contact', 0, '1'),
('ai_dictation_provider', 0, 'gpt'),
('ai_dictation_openai_model', 0, 'gpt-4o-mini'),
('ai_dictation_claude_model', 0, 'claude-haiku'),
('ai_dictation_gemma_model', 0, 'gemini-2.5-flash'),
('ai_dictation_gemma_region', 0, 'us-central1'),
('ai_dictation_ollama_endpoint', 0, 'http://localhost:11434'),
('ai_dictation_ollama_model', 0, 'custom'),
('ai_dictation_ollama_custom_model', 0, 'clinicalscribe'),
('ai_dictation_stt_engine', 0, 'chrome'),
('ai_dictation_whisper_endpoint', 0, 'http://localhost:9000'),
('ai_dictation_faster_whisper_endpoint', 0, 'http://127.0.0.1:9010'),
('ai_dictation_faster_whisper_model', 0, 'large-v3-turbo'),
('ai_dictation_faster_whisper_device', 0, 'auto'),
('ai_dictation_faster_whisper_compute_type', 0, 'auto'),
('ai_dictation_deepgram_api_key', 0, ''),
('ai_dictation_deepgram_model', 0, 'nova-3-medical'),
('ai_dictation_deepgram_custom_model', 0, ''),
('ai_dictation_deepgram_keyterms', 0, 'pelvic inflammatory disease, tubo-ovarian abscess, cervical motion tenderness, adnexal tenderness, CA-125, endometrial biopsy, vulvar lesion, labia majora, suprapubic tenderness, postmenopausal bleeding'),
('ai_dictation_deepgram_smart_format', 0, '1'),
('ai_dictation_deepgram_dictation', 0, '1'),
('ai_dictation_deepgram_measurements', 0, '1'),
('ai_dictation_language', 0, 'en-BS')
ON DUPLICATE KEY UPDATE gl_value = IF(gl_value = '', VALUES(gl_value), gl_value);
